"""Refresh the bundled catalog without executing source-site JavaScript."""
import json
import re
from pathlib import Path
from urllib.request import urlopen

SOURCE = 'https://gamers-hack.com/tftimg/set-18/'


def extract_catalog(html):
    match = re.search(r'\bconst\s+ITEMS\s*=\s*(?:/\*.*?\*/\s*)?', html, re.S)
    if not match:
        raise ValueError('Source catalog declaration not found')
    items, _ = json.JSONDecoder().raw_decode(html[match.end():])
    if not isinstance(items, list) or not items:
        raise ValueError('Empty or invalid catalog')
    result = {}
    for item in items:
        url, name = item.get('url'), item.get('name')
        if not isinstance(url, str) or not url.startswith('https://raw.githubusercontent.com/noxelisdev/TFT_DDragon/'):
            raise ValueError('Unexpected image URL')
        if not isinstance(name, str) or not name.strip():
            raise ValueError('Missing image name')
        result[url] = {'url': url, 'name': name[:140]}
    return list(result.values())


if __name__ == '__main__':
    with urlopen(SOURCE, timeout=30) as response:
        html = response.read(12 * 1024 * 1024 + 1)
    if len(html) > 12 * 1024 * 1024:
        raise ValueError('Source page too large')
    catalog = extract_catalog(html.decode('utf-8'))
    output = '// Generated by update_catalog.py from ' + SOURCE + '\nwindow.TFTCatalog = ' + json.dumps(catalog, ensure_ascii=False, separators=(',', ':')) + ';\n'
    Path(__file__).with_name('catalog.js').write_text(output, encoding='utf-8')
    print(f'Bundled {len(catalog)} images')
