import asyncio, json, io, base64, hashlib, math, time, os, shutil, subprocess, sys
from pathlib import Path
from PIL import Image, ImageDraw
from playwright.async_api import async_playwright
ROOT=Path(__file__).resolve().parents[1]; OUT=ROOT/'tests'/'output';OUT.mkdir(exist_ok=True)
if not (ROOT/'TFT-Thumbnail-Editor.html').exists(): subprocess.run([sys.executable,str(ROOT/'build_standalone.py')],check=True)
report=[]
def ok(name, condition=True, detail=''):
 assert condition, name+': '+str(detail)
 report.append({'test':name,'result':'PASS','detail':detail})
 print('PASS',name,flush=True)
def fixture(name,w,h,alpha=False):
 im=Image.new('RGBA' if alpha else 'RGB',(w,h),(0,0,0,0) if alpha else (32,58,90));d=ImageDraw.Draw(im)
 if alpha:d.rectangle((80,50,w-81,h-51),fill=(234,164,52,255));d.ellipse((120,100,w-121,h-151),fill=(80,35,138,255))
 else:d.rectangle((int(w*.5),0,w,h),fill=(87,57,112));d.ellipse((int(w*.55),int(h*.15),int(w*.95),int(h*.9)),fill=(225,170,70))
 path=OUT/name;im.save(path);return path
BG=fixture('fixture-bg.png',1920,1080)
CHAR=fixture('fixture-character.png',400,500,True)
ICON=fixture('fixture-icon.png',160,120)
async def main():
 async with async_playwright() as p:
  executable=os.environ.get('CHROMIUM_EXECUTABLE') or shutil.which('chromium') or shutil.which('chromium-browser')
  browser=await p.chromium.launch(**({'executable_path':executable} if executable else {}),args=['--no-sandbox'])
  context=await browser.new_context(viewport={'width':1540,'height':1000},device_scale_factor=1,accept_downloads=True)
  page=await context.new_page();page.set_default_timeout(6000); errors=[]
  page.on('pageerror',lambda e:errors.append(str(e)))
  await page.route('https://**/*',lambda r:r.abort())
  await page.set_content((ROOT/'TFT-Thumbnail-Editor.html').read_text(encoding='utf-8'),wait_until='domcontentloaded')
  await page.wait_for_function('TFTApp.getStatus().initialized')
  await page.wait_for_timeout(4500)
  ok('起動・ロゴ画像の復元',len(await page.evaluate('TFTApp.getAssetInfo()'))==1)
  ok('JavaScript例外なし（起動）',not errors,errors)
  ok('通信遮断時のフォント警告',await page.evaluate('TFTApp.getStatus().fontState')=='fallback')
  ok('保存領域制限時の代替案表示','自動保存' in await page.locator('#save-status').inner_text())
  # Rendering/math invariants across Japanese, Latin, very short/long text.
  check=await page.evaluate('''() => {const C=TFTCore,A=new Map(),results=[];for(const text of ['最強','ザヤ構成','ピルトーヴァー構成','WWWWWWWWWWWWWWWWWWWWWWWWWW','強'.repeat(100),'TFT18 / 100%','【圧倒的】新オーグ攻略！']){const s=C.defaultState();s.headline=text;const l=C.layout(s,A),o=l.objects.get('headline');results.push({text,w:o.w,h:o.h,b:C.bounds(o),font:l.mainFont,sub:l.subFont});}return results;}''')
  ok('赤文字の実寸フィット・縁取りの安全余白',all(r['w']<=1252.1 and r['h']<=244.1 and r['b']['bottom']<=702.1 for r in check),check)
  ok('白文字は赤文字より小さい',all(r['sub']<r['font'] for r in check))
  ok('長い赤文字ほど縮小',check[0]['font']>check[2]['font']>check[4]['font'])
  sub=await page.evaluate("() => {let s=TFTCore.defaultState();s.subtitle.text='新しいオーグメントを使って最強の盤面を完成させる方法を解説！';return TFTCore.layout(s,new Map()).objects.get('subtitle');}")
  ok('長い白文字を2行へ自動分割',len(sub['runs'])==2 and sub['w']<1229)
  # Background UI import and text selection.
  await page.locator('#background-picker').click(); await page.locator('#image-file').set_input_files(str(BG));await page.wait_for_function('TFTApp.getState().background.asset !== null')
  ok('背景ファイルをUIから追加',not await page.locator('#source-dialog').evaluate('(e)=>e.open'))
  await page.locator('#subtitle').fill('新オーグで一気に最強へ！')
  await page.locator('#subtitle').evaluate('(e)=>{e.focus();e.setSelectionRange(0,4);e.dispatchEvent(new Event("select"));}')
  await page.locator('#mark-yellow').click()
  marks=await page.evaluate('TFTApp.getState().subtitle.marks')
  ok('選択部分だけ黄色に変更',marks==[{'start':0,'end':4}],marks)
  await page.locator('#subtitle').fill('注目！新オーグで一気に最強へ！')
  marks=await page.evaluate('TFTApp.getState().subtitle.marks')
  ok('先頭に文字を挿入しても強調範囲を追従',marks==[{'start':3,'end':7}],marks)
  await page.locator('#subtitle').evaluate('(e)=>{e.focus();e.setSelectionRange(4,6);e.dispatchEvent(new Event("select"));}')
  await page.locator('#mark-white').click();marks=await page.evaluate('TFTApp.getState().subtitle.marks')
  ok('部分的な白戻し',marks==[{'start':3,'end':4},{'start':6,'end':7}],marks)
  await page.locator('#band-enabled').check();await page.locator('#logo-position [data-value="left"]').click()
  objs=await page.evaluate('TFTApp.getScene().objects')
  d={o['id']:o for o in objs}
  ok('ロゴ左上・黒帯と自由文字は反対側へ',d['logo']['x']<200 and d['band']['x']>640 and d['tag']['x']>640)
  await page.locator('#logo-position [data-value="right"]').click()
  # Import dedicated character and five overlay images.
  await page.locator('#tab-images').click();await page.locator('[data-open-source="character"]').click();await page.locator('#image-file').set_input_files(str(CHAR));await page.wait_for_function('TFTApp.getState().character !== null')
  charinfo=await page.evaluate('TFTApp.getAssetInfo().find(a=>a.id===TFTApp.getState().character.asset)')
  ok('透過キャラクターの余白を自動除去',charinfo['width']==240 and charinfo['height']==400,charinfo)
  order=await page.evaluate('TFTApp.getState().order');ok('キャラクターを背景と文字の間に配置',order.index('character')<order.index('headline'))
  await page.locator('#tab-images').click();await page.locator('#add-overlay').click();await page.locator('#image-file').set_input_files([str(ICON)]*5)
  await page.wait_for_function('TFTApp.getState().overlays.length === 5')
  await page.locator('#tab-images').click();ok('追加画像5枚で追加ボタン無効',await page.locator('#add-overlay').is_disabled())
  cap=await page.evaluate('''async () => {try {await TFTApp.importBlob(new Blob(['x']), 'overlay','six');return false;}catch(e){return e.message.includes('5');}}''')
  ok('API側でも6枚目を拒否',cap)
  overlayids=await page.evaluate('TFTApp.getState().overlays.map(x=>x.id)');target=overlayids[0]
  await page.locator('#tab-layers').click();await page.locator(f'#layer-list [data-select-layer="{target}"]').first.click()
  await page.locator('#layer-x').fill('620');await page.locator('#layer-x').press('Tab');await page.locator('#layer-y').fill('260');await page.locator('#layer-y').press('Tab')
  await page.locator('#layer-rotation').fill('30');await page.locator('#layer-rotation').press('Tab')
  await page.locator('#layer-opacity').fill('75');await page.locator('#layer-opacity').press('Tab')
  layer=await page.evaluate('(id)=>TFTApp.getState().overlays.find(x=>x.id===id)',target)
  ok('座標・回転・不透明度を数値で編集',layer['x']==620 and layer['y']==260 and layer['rotation']==30 and layer['opacity']==.75,layer)
  await page.locator('#layer-rotation').fill('0');await page.locator('#layer-rotation').press('Tab')
  # Put selected object in front, then direct drag/resize/rotate.
  for _ in range(12):await page.locator('[data-action="layer-up"]').click()
  box=await page.locator('#canvas').bounding_box(); sx=box['width']/1280;sy=box['height']/720
  def screen(x,y):return (box['x']+x*sx,box['y']+y*sy)
  await page.keyboard.press('Alt');a=screen(620,260);z=screen(715,315);await page.mouse.move(*a);await page.mouse.down();await page.mouse.move(*z,steps=6);await page.mouse.up();await page.keyboard.up('Alt')
  layer=await page.evaluate('(id)=>TFTApp.getState().overlays.find(x=>x.id===id)',target)
  ok('キャンバスで画像をドラッグ',abs(layer['x']-715)<12 and abs(layer['y']-315)<12,layer)
  obj=await page.evaluate('(id)=>TFTApp.getScene().objects.find(x=>x.id===id)',target)
  corner=(obj['x']+obj['w']/2,obj['y']+obj['h']/2);anchor=(obj['x']-obj['w']/2,obj['y']-obj['h']/2)
  newcorner=(anchor[0]+obj['w']*1.25,anchor[1]+obj['h']*1.25)
  await page.mouse.move(*screen(*corner));await page.mouse.down();await page.mouse.move(*screen(*newcorner),steps=8);await page.mouse.up()
  enlarged=await page.evaluate('(id)=>TFTApp.getState().overlays.find(x=>x.id===id)',target)
  ok('四隅ハンドルによる等比拡大',enlarged['w']>obj['w']*1.15,{'before':obj['w'],'after':enlarged['w']})
  obj=await page.evaluate('(id)=>TFTApp.getScene().objects.find(x=>x.id===id)',target);dist=obj['h']/2+28/sx
  start=(obj['x'],obj['y']-dist);end=(obj['x']+dist*.7071,obj['y']-dist*.7071)
  await page.keyboard.down('Shift');await page.mouse.move(*screen(*start));await page.mouse.down();await page.mouse.move(*screen(*end),steps=8);await page.mouse.up();await page.keyboard.up('Shift')
  angle=await page.evaluate('(id)=>TFTApp.getState().overlays.find(x=>x.id===id).rotation',target)
  ok('回転ハンドル・Shiftで15度刻み',abs(angle-45)<.1,angle)
  before=await page.evaluate('(id)=>TFTApp.getState().overlays.find(x=>x.id===id).x',target)
  await page.locator('#canvas').focus();await page.keyboard.press('Shift+ArrowRight');after=await page.evaluate('(id)=>TFTApp.getState().overlays.find(x=>x.id===id).x',target)
  ok('Shift＋矢印で10px移動',after==before+10)
  await page.locator('#layer-locked').check();await page.locator('#canvas').focus();await page.keyboard.press('ArrowRight');locked=await page.evaluate('(id)=>TFTApp.getState().overlays.find(x=>x.id===id).x',target)
  ok('ロックした位置は移動しない',locked==after)
  await page.locator('#layer-locked').uncheck()
  await page.locator(f'[data-visibility="{target}"]').click();ok('レイヤー非表示',target not in await page.evaluate('TFTApp.getScene().ids'))
  await page.locator(f'[data-visibility="{target}"]').click()
  await page.locator('[data-action="delete"]').click();ok('画像の削除',await page.evaluate('TFTApp.getState().overlays.length')==4)
  await page.locator('#undo').click();ok('削除を取り消す',await page.evaluate('TFTApp.getState().overlays.length')==5)
  await page.locator('#redo').click();ok('削除をやり直す',await page.evaluate('TFTApp.getState().overlays.length')==4)
  await page.locator('#undo').click()
  await page.locator(f'#layer-list [data-select-layer="{target}"]').first.click();await page.locator('[data-action="duplicate"]').click();ok('複製でも上限5枚を保つ',await page.evaluate('TFTApp.getState().overlays.length')==5)
  # IME guard / rich-text security / free text palette.
  await page.locator('#tab-basic').click();before=await page.evaluate('TFTApp.getState().headline')
  await page.locator('#headline').evaluate('(e)=>{e.dispatchEvent(new CompositionEvent("compositionstart",{bubbles:true}));e.value="変換途中";e.dispatchEvent(new InputEvent("input",{bubbles:true,isComposing:true}));}')
  await page.keyboard.press('Control+z');ok('日本語変換中は組版・undoを実行しない',await page.evaluate('TFTApp.getState().headline')==before)
  await page.locator('#headline').evaluate('(e)=>{e.value="最強の盤面へ";e.dispatchEvent(new CompositionEvent("compositionend",{bubbles:true}));}')
  ok('日本語変換確定を反映',await page.evaluate('TFTApp.getState().headline')=='最強の盤面へ')
  await page.locator('[data-action="add-text"]').click();free=await page.evaluate('TFTApp.getStatus().selected')
  await page.locator('#layer-text').fill('<img src=x onerror=alert(1)>')
  ok('入力文字をHTMLとして実行しない',await page.locator('#layer-list img[src="x"]').count()==0)
  await page.locator('#layer-text').fill('絶対に勝つ！');await page.locator('#text-color [data-value="white"]').click()
  ok('自由文字は指定3色のみ',await page.locator('#text-color button').count()==3 and await page.evaluate('(id)=>TFTApp.getState().texts.find(x=>x.id===id).color',free)=='white')
  await page.locator('#text-color [data-value="yellow"]').click();await page.locator('#text-double-outline').check()
  # Catalog parser and denied source behavior.
  catalog=await page.evaluate('''() => TFTSources.parseHTML('<a href="/full/xayah.png"><img src="/thumb/xayah.png" alt="ザヤ"></a><img data-src="https://assets.example/a.webp" alt="アイテム"><img src="javascript:alert(1)"><script>window.PWNED=true</script>','https://gamers-hack.com/tftimg/set-18')''')
  ok('素材HTMLを安全に解析・高解像度リンクを優先',any(x['url']=='https://gamers-hack.com/full/xayah.png' for x in catalog) and all(x['url'].startswith('http') for x in catalog) and await page.evaluate('!window.PWNED'),catalog)
  await page.locator('#tab-basic').click();await page.locator('[data-start-tab="site"]').click();await page.wait_for_timeout(1000)
  notice=await page.locator('#source-notice').inner_text();ok('指定サイト取得失敗を明示','読み込め' in notice or '制限' in notice or '取得でき' in notice,notice)
  await page.locator('#source-dialog [data-close-dialog]').click()
  # Export: strict font gate; allowance; actual downloads.
  await page.locator('[data-action="export"]').click()
  ok('指定フォント未読込なら書き出しをブロック',await page.locator('#export-download').is_disabled())
  await page.locator('#allow-fallback').check();await page.locator('#export-size [data-value="1920"]').click()
  async with page.expect_download() as event:await page.locator('#export-download').click()
  download=await event.value;await download.save_as(str(OUT/'export-1920.png'))
  image=Image.open(OUT/'export-1920.png');ok('PNGを1920×1080で実際に書き出し',image.size==(1920,1080) and image.format=='PNG',{'size':image.size,'bytes':(OUT/'export-1920.png').stat().st_size})
  await page.locator('#export-format [data-value="jpeg"]').click();await page.locator('#export-size [data-value="2560"]').click()
  async with page.expect_download() as event:await page.locator('#export-download').click()
  download=await event.value;await download.save_as(str(OUT/'export-2560.jpg'))
  image=Image.open(OUT/'export-2560.jpg');ok('JPEGを2560×1440で実際に書き出し',image.size==(2560,1440) and image.format=='JPEG')
  await page.locator('#export-format [data-value="png"]').click();await page.locator('#export-size [data-value="1280"]').click()
  await page.locator('#export-dialog [data-close-dialog]').click()
  hashjs="async()=>{const b=await TFTApp.createExportBlob();return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',await b.arrayBuffer()))).join(',')}"
  # crypto.subtle is unavailable on an opaque test origin; compare bytes directly.
  hashjs="async()=>{const b=await TFTApp.createExportBlob();const a=new Uint8Array(await b.arrayBuffer());let h=0;for(const x of a)h=(h*31+x)|0;return [h,a.length]}"
  first=await page.evaluate(hashjs);await page.locator('[data-action="guides"]').click();second=await page.evaluate(hashjs);ok('ガイド表示の有無で完成PNGは変わらない',first==second)
  await page.locator('[data-action="guides"]').click()
  # File save/reopen round-trip and atomic rejection.
  await page.locator('[data-action="project-menu"]').click()
  async with page.expect_download() as event:await page.locator('[data-action="save-project"]').click()
  download=await event.value;await download.save_as(str(OUT/'roundtrip.tft.json'))
  doc=json.loads((OUT/'roundtrip.tft.json').read_text());ok('画像を内包した編集プロジェクトを保存',doc['kind']=='tft-thumbnail-project' and len(doc['assets'])==7,{'assetCount':len(doc['assets'])})
  ok('保存データにフォントバイナリなし',all(a['data'].startswith('data:image/') for a in doc['assets']))
  old=await page.evaluate('TFTApp.getState()')
  await page.evaluate('async text=>await TFTApp.loadProjectFile(new File([text],"roundtrip.tft.json",{type:"application/json"}),false)',json.dumps(doc,ensure_ascii=False))
  new=await page.evaluate('TFTApp.getState()')
  ok('プロジェクト再読込で文章・強調・重ね順・変形を復元',new['headline']==old['headline'] and new['subtitle']==old['subtitle'] and new['order']==old['order'] and all(new['overlays'][i]['rotation']==old['overlays'][i]['rotation'] for i in range(5)))
  ok('再読込時の画像ID衝突を回避',new['background']['asset']!=old['background']['asset'])
  bad=json.loads(json.dumps(doc));bad['assets'][1]['data']='data:image/png;base64,INVALID'
  nassets=len(await page.evaluate('TFTApp.getAssetInfo()'))
  result=await page.evaluate('''async text=>{try{await TFTApp.loadProjectFile(new File([text],'bad.json'),false);return false;}catch(e){return true;}}''',json.dumps(bad))
  ok('壊れたプロジェクトは既存状態・素材を変えずに拒否',result and new==await page.evaluate('TFTApp.getState()') and nassets==len(await page.evaluate('TFTApp.getAssetInfo()')))
  cap=await page.evaluate('''() => {const s=TFTCore.defaultState();s.overlays=new Array(6).fill({});try{TFTCore.validate(s);return false;}catch(e){return true;}}''');ok('読み込みプロジェクトにも上限検証',cap)
  badimage=await page.evaluate('''async()=>{try{await TFTApp.importBlob(new Blob(['<svg xmlns="http://www.w3.org/2000/svg"/>'],{type:'image/png'}),'background','fake.png');return false;}catch(e){return e.message;}}''')
  ok('拡張子を偽装したSVGを拒否',isinstance(badimage,str) and '形式' in badimage,badimage)
  # Responsive UI, dialog containment.
  await page.locator('#tab-basic').click();await page.locator('#headline').focus();await page.locator('#headline').evaluate('e=>e.scrollIntoView({block:"center"})')
  await page.wait_for_timeout(1000);await page.screenshot(path=str(OUT/'desktop.png'),full_page=True)
  await page.set_viewport_size({'width':390,'height':844});await page.evaluate('window.scrollTo(0,0)');await page.wait_for_timeout(300)
  ok('390px幅で横スクロールなし',await page.evaluate('document.documentElement.scrollWidth <= innerWidth'))
  await page.screenshot(path=str(OUT/'mobile.png'),full_page=True)
  await page.locator('[data-action="export"]').click();await page.wait_for_timeout(200);r=await page.locator('#export-dialog').bounding_box()
  ok('モバイルでも書き出しダイアログが収まる',r['x']>=0 and r['x']+r['width']<=391,r)
  await page.screenshot(path=str(OUT/'mobile-export.png'),full_page=True)
  await page.locator('#export-dialog [data-close-dialog]').click()
  ok('一連のUI操作中にJavaScript例外なし',not errors,errors)
  # Save exact tested viewport / engine for transparent test documentation.
  result={'engine':browser.version,'execution':'Chromium DOM injection of standalone HTML; network/font requests denied; opaque-origin persistence fallback tested','tests':report,'pageErrors':errors}
  (OUT/'test-report.json').write_text(json.dumps(result,ensure_ascii=False,indent=2))
  await browser.close()
asyncio.run(main())
